version: '3.8'
services:
  db:
    image: "postgres:15"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "sectorsdb"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d
volumes:
  db-data:
